name: Master Codecov Report

on:
  push:
    branches: [master]

concurrency: ${{ github.workflow }}

jobs:
  report-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v4

      - name: Build for test
        run: pnpm -r build:test

      - name: Test
        run: pnpm ci:test

      - name: Codecov Core
        uses: codecov/codecov-action@v4
        with:
          flags: core
          directory: ./packages/core
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codecov UI
        uses: codecov/codecov-action@v4
        with:
          flags: experience
          directory: ./packages/experience
          token: ${{ secrets.CODECOV_TOKEN }}
