name: Repository Dispatch

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}

jobs:
  event_dispatch:
    strategy:
      matrix:
        target: [logto-io/cloud]
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          repository: ${{ matrix.target }}
          event-type: ${{ github.event_name }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
